name: ReadyAPI Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  readyapi_tests:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code from the repository
    - name: Checkout code
      uses: actions/checkout@v3
      
    # Set up JDK (ReadyAPI requires Java)
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
    
    # Download and extract ReadyAPI (if not already installed on your machine)
    - name: Download ReadyAPI
      run: |
        curl -L -o readyapi.tar.gz https://smartbearsoftware-my.sharepoint.com/personal/your_username/_layouts/15/SPRequest.aspx?content=download&url=https://your_download_link&action=download
        tar -xvf readyapi.tar.gz
        export READYAPI_HOME=$(pwd)/readyapi-x.y.z
        
    # Run ReadyAPI tests using the CLI
    - name: Run ReadyAPI Tests
      run: |
        $READYAPI_HOME/bin/readyapi.sh -s"TestSuite" -t"TestCase" -f"HTML" -r"results" -j"result.json"
        
    # Upload test results (optional)
    - name: Upload test results
      uses: awalsh128/cache-apt-pkgs-action@v1.4.3
      with:
        name: readyapi-test-results
        path: results/
